### ISSUE TITLE
An error report

### ISSUE THREAD

**Issue by Ruoyu66666** [yjhp1016/taichi_LBM3D#19]
Hi,

This is Ruoyu. I found a small issue in the function meq_vec:
@ti.func
def meq_vec(rho_local,u):
    out = ti.Vector([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
    out[0] = rho_local;             out[3] = u[0];    out[5] = u[1];    out[7] = u[2];
    out[1] = u.dot(u);    out[9] = 2*u.x*u.x-u.y*u.y-u.z*u.z;         out[11] = u.y*u.y-u.z*u.z
    out[13] = u.x*u.y;    out[14] = u.y*u.z;                            out[15] = u.x*u.z
    return out

All the non-zero meq component should have density component, but the meq[k] except for meq[0] does not contain rho_local.

Regards,

Ruoyu

**Comment by Ruoyu66666** [comment]
Also, a few components of meq is missed out, such as meq[8], meq[12], etc.

**Comment by Ruoyu66666** [comment]
Hi Jianhui,

Thanks for your reply. What is the paper you are referring to? The attachment is not seeable.

Regards,

Ruoyu

**Comment by yjhp1016** [comment]
Here it is:

Ahrenholz, B., et al. "Prediction of capillary hysteresis in a porous
material using lattice-Boltzmann methods and comparison to experimental
data and a morphological pore network model." *Advances in Water
Resources* 31.9
(2008): 1151-1173.

**Comment by Ruoyu66666** [comment]
Thank you Jianhui, I'll check it out.
