### ISSUE TITLE
Communication Request

### ISSUE THREAD

**Issue by Ruoyu66666** [yjhp1016/taichi_LBM3D#23]
Hi Jianhui,

My name is Ruoyu Li, a PhD student working on LBMs. I would like to contribute to Taichi-LBM with the use of mpi4py to parallelize taichi jobs on multiple GPUs. Now I'm in the testing phase. Is it possible to know your wechat id to ease communications? My email is liruoyu@utexas.edu. Thank you.

Regards,

Ruoyu

**Comment by yjhp1016** [comment]
Hi Ruoyi,

Thanks for your interest and contribution. We appreciate your contribution.
My wechat is yjhp1016


Ruoyu66666.github.io ***@***.***> 于 2023年12月29日周五 上午8:23写道：
